apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdbserver-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdbserver
  template:
    metadata:
      labels:
        app: mdbserver
    spec:
      containers:
        - name: mdbserver
          image: codethedream/mdbserver
          env:
            - name: MONGO_URI
              value: "mongodb+srv://matamandokalilani:Allin1Allin1@cluster0.8bpgadj.mongodb.net/?retryWrites=true&w=majority"

---
apiVersion: v1
kind: Service
metadata:
  name: mdbserver-srv
spec:
  selector:
    app: mdbserver
  ports:
    - name: mdbserver
      protocol: TCP
      port: 3000
      targetPort: 3000