apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdbworker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdbworker
  template:
    metadata:
      labels:
        app: mdbworker
    spec:
      containers:
        - name: mdbworker
          image: codethedream/mdbworker
          env:
            - name: MONGO_URI
              value: "mongodb+srv://matamandokalilani:Allin1Allin1@cluster0.8bpgadj.mongodb.net/?retryWrites=true&w=majority"

---
apiVersion: v1
kind: Service
metadata:
  name: mdbworker-srv
spec:
  selector:
    app: mdbworker
  ports:
    - name: mdbworker
      protocol: TCP
      port: 3000
      targetPort: 3000
